name: Azure Python 3.12

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install dependencies
        run: make install-cloud

      - name: Lint
        run: make lint-cloud

      - name: Test
        run: make test-cloud

  build-and-push:
    runs-on: ubuntu-latest
    needs: build  # wait for tests to pass
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image using Makefile
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/ppg_ms
          TAG: latest
        run: make run-cloud-container
